package org.dmkr.chess.api.model;

public interface Constants {
	
	// colors
	byte VALUE_WHITE = 1;
	byte VALUE_BLACK = -1;
	
	// pieces
	byte VALUE_KING = 6;
	byte VALUE_QUEEN = 5;
	byte VALUE_ROOK = 4;
	byte VALUE_BISHOP = 3;
	byte VALUE_KNIGHT = 2;
	byte VALUE_PAWN = 1;
	byte VALUE_EMPTY = 0;
	
	// special moves
	int SPECIAL_MOVE_NO = 0 << 24;
	int SPECIAL_MOVE_PAWN_TO_QUEEN = VALUE_QUEEN << 24;
	int SPECIAL_MOVE_PAWN_TO_ROOK = VALUE_ROOK << 24;
	int SPECIAL_MOVE_PAWN_TO_BISHOP = VALUE_BISHOP << 24;
	int SPECIAL_MOVE_PAWN_TO_KNIGHT = VALUE_KNIGHT << 24;
	int SPECIAL_MOVE_PAWN_GOES_TWO_STEPS = 10 << 24;
	int SPECIAL_MOVE_PAWN_EN_PASSANT = 11 << 24;
	int SPECIAL_MOVE_CASTELING_LEFT_DISSALOW_CASTELING_LEFT = 12 << 24;
	int SPECIAL_MOVE_CASTELING_LEFT_DISSALOW_CASTELING_BOTH = 13 << 24;
	int SPECIAL_MOVE_CASTELING_RGHT_DISSALOW_CASTELING_RGHT = 14 << 24;
	int SPECIAL_MOVE_CASTELING_RGHT_DISSALOW_CASTELING_BOTH = 15 << 24;
	int SPECIAL_MOVE_DISSALOW_CASTELING_LEFT = 16 << 24;
	int SPECIAL_MOVE_DISSALOW_CASTELING_RGHT = 17 << 24;
	int SPECIAL_MOVE_DISSALOW_CASTELING_BOTH = 18 << 24;
	
	int SIZE = 8;
	int NUMBER_OF_PIECES = 6;
}
